MakeAWishFoundation/SwiftyMocky

AutoEquatable.generated.swift, Example/Mocky.xcodeproj/project.pbxproj, Example/Mocky/Base.lproj/LaunchScreen.xib, Example/Mocky/Item.swift, Example/Mocky/ItemsModel.swift, Example/Podfile.lock, Example/Rakefile, Example/Tests/Mock.generated.swift, Example/Tests/Mocks/ItemsClientMock.swift, Example/Tests/Mocks/ItemsModelMock.swift, Example/Tests/Mocks/ItemsRepositoryMock.swift, Example/Tests/XCTests/ItemsModelTests.swift, Example/Tests/XCTests/ItemsViewModelTests.swift, Mocky/Classes/Parameter.swift
=> Revert "added matcher proposition"

Example/Mocky/ExampleProtocols.swift, Mocky/Templates/Mock.swifttemplate
Changed way of verifying if two methods are same (for sake of allMethods filtering), so to create stubs only for unique ones.
=> feat: handling unique methods for default values case

Example/Tests/Mocks/ItemsRepositoryMock.swift, Example/Tests/Mocks/Mock.generated.swift, Mocky/Classes/Matcher.swift, Mocky/Classes/Mock+Assertions.swift, Mocky/Classes/Mock.swift, Mocky/Classes/Parameter.swift, Mocky/Templates/Mock.swifttemplate
Added prints and fatalErrors, to at least provide runtime crash info.
=> feat: error handling, docs update

Mocky.xcodeproj/project.pbxproj, Sources/Templates/Mock.swifttemplate, SwiftyMocky-Example/Mocky/ProtocolsWithCollections.swift, SwiftyMocky-Example/Mocky/SimpleProtocols.swift, SwiftyMocky-Example/Tests/Example 1/ProtocolsWithCollectionsTests.swift, SwiftyMocky-Example/Tests/Example 1/SimpleProtocolsTests.swift, SwiftyMocky-Example/Tests/Mocks/Mock.generated.swift, guides/Examples.md
Featuring:
- simple example 1
- fix for optional parameters getter generation
=> Feature/docs examples section - example 1

Mocky.xcodeproj/project.pbxproj, Sources/Templates/Mock.swifttemplate, SwiftyMocky-Example/Mocky/ProtocolWithThrowingMethods.swift, SwiftyMocky-Example/Tests/Example 2/ProtocolWithThrowingMehtodsTests.swift, SwiftyMocky-Example/Tests/Mocks/ItemsRepositoryMock.swift, SwiftyMocky-Example/Tests/Mocks/Mock.generated.swift, guides/Examples.md
Featuring:
+ fixed throw and return values handling
+ added example 2 for throwing methods
=> feat: guides example 2 + throwing fix

Mocky.xcodeproj/project.pbxproj, SwiftyMocky-Example/Mocky/ProtocolsWithCustomAttributes.swift, SwiftyMocky-Example/Tests/Example 1/ProtocolsWithCollectionsTests.swift, SwiftyMocky-Example/Tests/Example 3/ProtocolsWithCustomAttributesTests.swift, SwiftyMocky-Example/Tests/Mocks/Mock.generated.swift, guides/Examples.md
Featuring:
- tests and example for custom attributes (using Matcher)
=> feat: guides example 3

README.md, SwiftyMocky.podspec, guides/CHANGELOG.md
Added changelog. Prepared spec for 1.0.0 release.
=> feat: adds changelog, update spec

Sources/Classes/Matcher.swift, SwiftyMocky-Example/Tests/Example 1/SimpleProtocolsTests.swift, SwiftyMocky-Example/Tests/Example 7/ProtocolsWithGenericsTests.swift, SwiftyMocky-Example/Tests/XCTests/ExampleTests.swift, guides/Generics.md, guides/Known issues.md
=> feat: added all basic types to matcher, updated docs

README.md, SwiftyMocky-Example/Runtime/Info.plist, SwiftyMocky.podspec
=> feat: updated readme, bumped version to 1.0.2

Podfile.lock, Sources/Classes/Parameter.swift, SwiftyMocky-Example/Tests/Example 1/SimpleProtocolsTests.swift, SwiftyMocky-Example/Tests/XCTests/ExampleTests.swift
Resolves #59 
Adds more flexibility to parameter matching.
=> feat: added .matching case for parameter

README.md
Stumbled across the project and noticed a small typo in the readme.
=> Fix Minor Typo

.gitignore, Podfile.lock, Sources/Templates/Mock.swifttemplate, SwiftyMocky-Example/Shared/Example 7/ProtocolsWithGenerics.swift, SwiftyMocky-Tests/iOS/Mocks/Mock.generated.swift, SwiftyMocky-Tests/macOS/Mocks/Mock.generated.swift, SwiftyMocky-Tests/tvOS/Mocks/Mock.generated.swift
=> Fixed issue with generics not recognized as generics

Sources/Classes/Parameter.swift, SwiftyMocky-Example/Shared/Example 1/ProtocolsWithCollections.swift, SwiftyMocky-Tests/Shared/Example 1/ProtocolsWithCollectionsTests.swift, SwiftyMocky-Tests/iOS/Mocks/Mock.generated.swift, SwiftyMocky-Tests/macOS/Mocks/Mock.generated.swift, SwiftyMocky-Tests/tvOS/Mocks/Mock.generated.swift
=> Fixed issue for dictionaries in protocols with Swift 4.1

Podfile, Podfile.lock, Sources/Templates/Mock.swifttemplate, SwiftyMocky-Tests/Shared/Example 3/ProtocolsWithCustomAttributesTests.swift, SwiftyMocky-Tests/iOS/Mocks/ItemsRepositoryMock.swift, SwiftyMocky-Tests/iOS/Mocks/Mock.generated.swift, SwiftyMocky-Tests/macOS/Mocks/ItemsRepositoryMock.swift, SwiftyMocky-Tests/macOS/Mocks/Mock.generated.swift, SwiftyMocky-Tests/tvOS/Mocks/ItemsRepositoryMock.swift, SwiftyMocky-Tests/tvOS/Mocks/Mock.generated.swift, get_sourcery.sh
This PR solves issues with new Xcode, that was issued in #124.
=> Handle errors from compilation using xcode 10 beta 6

Mocky.xcodeproj/project.pbxproj, Sources/Templates/Mock.swifttemplate, SwiftyMocky-Example/Shared/Other/EdgeCasesProtocols.swift, SwiftyMocky-Tests/Shared/Other/EdgeCasesTests.swift, SwiftyMocky-Tests/iOS/Mocks/Mock.generated.swift, SwiftyMocky-Tests/macOS/Mocks/Mock.generated.swift, SwiftyMocky-Tests/tvOS/Mocks/Mock.generated.swift
Fixes #138 
Redone generic type check in type. Added more or less proper regex'ed, instead of previous partial solutions.
=> Updated generics, fixed resolving generic with custom type

Mocky.xcodeproj/project.pbxproj, Sources/Classes/SwiftyMockyTestObserver.swift
Fixed (hopefully) problems with pod trunk validation
=> Fixed errors from pod trunk validation

.mocky.iOS.yml, .mocky.macOS.yml, .mocky.tvOS.yml, Sources/Templates/Mock.swifttemplate, SwiftyMocky-Tests/iOS/Mocks/Mock.generated.swift, SwiftyMocky-Tests/macOS/Mocks/Mock.generated.swift, SwiftyMocky-Tests/tvOS/Mocks/Mock.generated.swift
according to #152 
**To discuss:**
Is naming (`swiftyMocky`) is OK?
**Other**
This changes should be included in #155
=> support for `swiftyMocky` key in configuration file

Sources/Templates/Mock.swifttemplate, SwiftyMocky-Tests/iOS/Mocks/ItemsRepositoryMock.swift, SwiftyMocky-Tests/iOS/Mocks/Mock.generated.swift, SwiftyMocky-Tests/macOS/Mocks/ItemsRepositoryMock.swift, SwiftyMocky-Tests/macOS/Mocks/Mock.generated.swift, SwiftyMocky-Tests/tvOS/Mocks/ItemsRepositoryMock.swift, SwiftyMocky-Tests/tvOS/Mocks/Mock.generated.swift, Templates/Main.swifttemplate, Templates/MethodWrapper.swift, Templates/Mock.swifttemplate, Templates/SubscriptWrapper.swift, Templates/VariableWrapper.swift
=> Make generated mock classes open by default

Package.resolved, Package.swift, Sources/SwiftyMockyCLICore/Commands/MacOS/InspectionController.swift, Sources/SwiftyMockyCLICore/Commands/MacOS/MigrationController.swift, Sources/SwiftyMockyCLICore/Commands/MacOS/ProjectSetupController.swift, Sources/SwiftyMockyCLICore/Utils/MacOS/XCodeProj+Extensions.swift, Sources/SwiftyMockyCLICore/Utils/ProjectFile.swift
It should fix "Error: The element XCRemoteSwiftPackageReference is not supported."
=> Support Xcode 11: Update xcodeproj to 7.1.0

Mintfile, Podfile.lock, Sources/CLI/Core/Utils/Global.swift, Sources/SwiftyMocky/Mock.swifttemplate, Sources/SwiftyPrototype/Prototype.swifttemplate, SwiftyMocky-Tests/iOS/Mocks/Mock.15.generated.swift, SwiftyMocky-Tests/iOS/Mocks/Mock.generated.swift, SwiftyMocky-Tests/macOS/Mocks/Mock.generated.swift, SwiftyMocky-Tests/tvOS/Mocks/Mock.generated.swift, SwiftyMocky.podspec, SwiftyPrototype.podspec, Templates/Header-Mock.swifttemplate, Templates/Header-Prototype.swifttemplate, Tests/SwiftyMockyCLICoreTests/Mock.generated.swift, Tests/SwiftyMockyTests/Mock.generated.swift
Fixes #306 by bumping to the latest Sourcery version.
=> Bumps Sourcery dependency to 1.8.0

.github/workflows/master.yml, Package.resolved, Package.swift
I carefully read https://github.com/MakeAWishFoundation/SwiftyMocky/blob/master/CONTRIBUTING.md
But the `develop` branch extremely outdated.
So I had to use `master` branch as target for this PR.
=> Actualize Yams dependency version
